---
title: "Well failure forecast"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    social: "menu" 
    source_code: "https://github.com/richpauloo/aife"
runtime: shiny_prerendered
---

```{r, context = "setup", include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(flexdashboard)
library(shiny)
library(shinyWidgets)
library(tidyverse)
library(leaflet)
library(plotly)

# toy data
#em <-  mapview::mapview(breweries91) %>% mapedit::editMap()
#write_rds(em, "C:/Users/rpauloo/Documents/Github/aife/shiny/breweries.rds")
#em <- read_rds("C:/Users/rpauloo/Documents/Github/aife/shiny/data/breweries.rds")
#em <- read_rds("~/Github/aife/shiny/data/breweries.rds")
em <- read_rds("data/breweries.rds")
em$drawn$priority <- factor(c("high","medium","low"), levels = c("high","medium","low"))
em$drawn$gsa      <- c("Kern","Tulare","Kings","Kaweah","Shasta","Sacramento")
em$drawn$min_threshold  <- c(50,55,60,65,70,75)
em$drawn$min_objective  <- em$drawn$min_threshold - 15

set.seed(1)
breweries91$pump_depth <- sample(seq(1,100,1), nrow(breweries91), replace = FALSE)
breweries91 <- sf::st_intersection(em$drawn,sf::st_as_sf(breweries91))
range <- c(mean(sf::st_bbox(em$drawn)[c(1,3)]), 
           mean(sf::st_bbox(em$drawn)[c(2,4)]))
range_all <- split(em$drawn, em$drawn$gsa) %>% 
  lapply(function(x) return(c(mean(sf::st_bbox(x)[c(1,3)]), 
                              mean(sf::st_bbox(x)[c(2,4)])))
         )

# toy data for well failure plot
sigmoid = function(x) {
   1 / (1 + exp(-x))
}

# color palette for markers
#pal <- colorFactor(c("red", "blue","green"), domain = c("high", "medium","low"))
pal_points <- function(data) {
  sapply(data$fail, function(x) {
  if(x == TRUE) {
    "red"
  } else {
    "blue"
  }
})
}

# palette for gsa polygons
pal_polygons <- colorFactor(c("#542788", "#35978f","#dfc27d"), domain = c("high", "medium","low"))
```


Directions {.sidebar}
-----------------------------------------------------------------------

#### Select a GSA:
```{r}
# drop down menu to select a GSA
pickerInput(
     inputId = "input_gsa",
     label = NULL, 
     choices = 
       list(
         "All",
        `High priority`   = c("Kern","Kaweah"), 
        `Medium priority` = c("Tulare","Sacramento"),
        `Low priority`    = c("Kings","Shasta")),
     selected = "All",
     options = list(
        style = "btn-primary")
)
```

#### Groundwater decline (ft):
```{r}
# slider input to select a groundwater level decline
sliderInput(
  inputId = "input_gwl", 
  label = NULL,
  min = 0, max = 100,
  value = 0, step = 5, 
  post = " ft."
)
```

#### Jump to scenario:
```{r}
# scenarios
#awesomeRadio(
radioButtons(
  inputId = "input_scenario",
  label = NULL, 
  #choices = c("specified groundwater decline", "minimum objective", "minimum threshold"),
  choices = c("specified groundwater decline"),
  selected = "specified groundwater decline"
)
```

```{r}
# actionBttn(
#   inputId = "input_help",
#   label = "adfdsf",
#   style = "material-circle",
#   color = "primary",
#   icon = icon("info")
# )
actionButton("input_help", "Instructions")
```


```{r, context = "server"}
# when the GSA changes in the dropdown menu, update the slider values
# relative to that GSA's min objective and threshold
observe({
  
  selected_gsa <- filter(em$drawn, gsa == input$input_gsa)

  val <- switch(
    input$input_scenario,
    "specified groundwater decline" = input$input_gwl,
    "minimum threshold" = selected_gsa$min_threshold,
    "minimum objective" = selected_gsa$min_objective
  )
  # Control the slider value
  updateSliderInput(session, "input_gwl", value = val)
})

observe({
  
  if(input$input_gsa == "All"){
    x <- "specified groundwater decline"
  } else
    x <-  c("specified groundwater decline", "minimum objective", "minimum threshold")
  
  # Control the slider value
  updateRadioButtons(session, "input_scenario", choices = x, selected = input$input_scenario)#"specified groundwater decline")
})
```


```{r, context="server"}
reactive_gwl <- reactive({ return(input$input_gwl) })

output$output_plotly <- renderPlotly({
  p <- tibble(gwl = seq(0,100, 5), 
              n   = sigmoid(round(seq(-5,5, 0.5),0))*32) %>% 
  mutate(lab = glue::glue("<b>GWL decline (ft):</b> {gwl} <br>",
                          "<b>n failures:</b> {round(n,0)} <br>",
                          "<b>Estimated Cost:</b> ${round(100*n,0)}")) %>% 
  ggplot(aes(gwl, n, text= lab)) +
  geom_rect(xmin=0, xmax=reactive_gwl(), ymin=0, ymax=32, fill = "red", alpha = 0.01) +
    geom_point() +
  labs(x = "Uniform groundwater level decline from current conditions",
       y = "Estimated number of well failures")
  
  p <- ggplotly(p, tooltip = "lab")
  for(i in 1:21){p$x$data[[i]]$text <- "region of groundwater \nlevel decline"}
  return(p)
})
```

```{r, context = "server"}
reactive_pts  <- reactive({ 
  if(input$input_gsa == "All") {
    return(filter(breweries91,
           pump_depth > input$input_gwl))
  } 
  if(input$input_gsa != "All") {
    return(filter(breweries91, 
           pump_depth > input$input_gwl & 
           gsa == input$input_gsa))
  }
})

reactive_pts_color  <- reactive({ 
  if(input$input_gsa == "All") {
    return(mutate(breweries91,
           fail = ifelse(input$input_gwl > pump_depth, TRUE, FALSE)))
  } 
  if(input$input_gsa != "All") {
    return(filter(breweries91, gsa == input$input_gsa) %>% 
             mutate(fail = ifelse(input$input_gwl > pump_depth, TRUE, FALSE)))
  }
})

reactive_poly <- reactive({ 
  if(input$input_gsa == "All") {
    return(em$drawn) 
  }
  if(input$input_gsa != "All") {
    return(filter(em$drawn, gsa == input$input_gsa))
  }
})

reactive_range <- reactive({
  if(input$input_gsa == "All"){
    return(range)
  } 
  if(input$input_gsa != "All") {
    return(range_all[[input$input_gsa]])
  }
})

output$output_map <- renderLeaflet({
  #if(nrow(reactive_pts()) > 0) {
    icons <- awesomeIcons(
      icon = 'ios-home',
      iconColor = 'black',
      library = 'ion',
      markerColor = pal_points(reactive_pts_color())
    )
    reactive_poly() %>% 
      leaflet() %>% 
      addProviderTiles(providers$CartoDB.Positron) %>% 
      addPolygons(label = ~gsa, color = ~pal_polygons(priority)) %>% 
      addAwesomeMarkers(data = reactive_pts_color(), label = ~pump_depth, icon=icons) %>% 
      setView(lng = reactive_range()[1], lat = reactive_range()[2], zoom = 8) %>% 
      addLegend("bottomright", pal = pal_polygons, values = ~priority, 
                title = "Basin \nprioritization")
  #} else
    # reactive_poly() %>% 
    #   leaflet() %>% 
    #   addTiles() %>%
    #   addPolygons(label = ~gsa) %>% 
    #   setView(lng = reactive_range()[1], lat = reactive_range()[2], zoom = 8)
})
```

```{r, context = "server"}
# observeEvent(input$input_help, {
#   sendSweetAlert(
#     session = session,
#     title = "Help",
#     text = "Instructions on how to use the dashboard.",
#     type = "info"
#   )
# })
observeEvent(input$input_help, {
      showModal(modalDialog(
        title = "How to use this dashboard",
        "Instrucitons, instructions, instructions. <b>bold</b>. `code` markdown",
        easyClose = TRUE
      ))
    })
```

```{r, context = "server"}
output$output_vb1 <- renderValueBox(
  if(input$input_gsa != "All") {
    valueBox(nrow(filter(breweries91, gsa == input$input_gsa)) - nrow(reactive_pts()), 
             icon = "fa-times-circle", color = "danger")
  } else
    valueBox(nrow(breweries91) - nrow(reactive_pts()), icon = "fa-times-circle", color = "danger")
)

output$output_vb2 <- renderValueBox(
  if(input$input_gsa != "All") {
    valueBox(paste0(round(((nrow(filter(breweries91, gsa == input$input_gsa)) - nrow(reactive_pts())) /
                             nrow(filter(breweries91, gsa == input$input_gsa)))*100, 2),"%"), 
             icon = "fa-percentage", color = "warning")
  } else
    valueBox(paste0(round(((nrow(breweries91) - nrow(reactive_pts())) / 
                             nrow(breweries91))*100, 2),"%"), 
             icon = "fa-percentage", color = "warning")
)

output$output_vb3 <- renderValueBox(
  if(input$input_gsa != "All") {
    valueBox(paste0("$", (nrow(filter(breweries91, gsa == input$input_gsa)) - nrow(reactive_pts())) * 100), 
             icon = "fa-money-check-alt", color = "success")
  } else
    valueBox(paste0("$", (nrow(breweries91) - nrow(reactive_pts())) * 100), icon = "fa-money-check-alt", color = "success")
)
```


Column
-----------------------------------------------------------------------

### Forecasted failures
```{r}
valueBoxOutput("output_vb1")
```

### Percentage of failing wells
```{r}
valueBoxOutput("output_vb2")
```

### Estimated Cost
```{r}
valueBoxOutput("output_vb3")
```


Column
-----------------------------------------------------------------------

### Map
```{r}
leafletOutput("output_map")
```

### Well failures
```{r}
plotlyOutput("output_plotly")
```

