---
title: "GSP_Steps"
author: "Darcy Bostic"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# set location
knitr::opts_knit$set(root.dir = "~/Desktop/aife/ForRich/")

# load packages needed
library(tidyverse)
library(sf)
library(dplyr)
library(mapview)
library(ggplot2)
theme_set(theme_bw())
library(dismo)     # for cross validation
library(gstat)     # for kirging and idw
library(automap)
library(raster) 
```

## Add monitoring networks 

```{r Load data}
# csv names
monitoring_network <- list.files("~/Desktop/aife/ForRich/RawData/MinimumThresholdShapefiles/", pattern = "\\.shp$")

# remove coastal GSPs - Borrego, Cuyama, Santa Cruz, PasoRobles, Salinas, Oxnard, Pleasant Valley
monitoring_network <- monitoring_network[-c(3, 8, 14:16, 21, 36, 39, 40)]

# data list
mn <- list() 

for(i in 1:length(monitoring_network)){
  mn[[i]] = st_read(file.path("~/Desktop/aife/ForRich/RawData/MinimumThresholdShapefiles/", monitoring_network[i]), stringsAsFactors = FALSE)
}
```

```{r Depth to Water compiled}
for(i in 1:length(mn)){
 mn[[i]]$MT_dtw <- as.numeric(as.character(mn[[i]]$MT_dtw))
}

for(i in 1:length(mn)){
  mn[[i]] <- subset(mn[[i]], select = c("Well_ID", "MT_dtw"))
}
```

## Read in WSEs and Difference MTs and WSE
```{r Load data}
# pull in minimum thresholds from compile_MTs.Rmd
MTs <- mn
getwd()
# pull in fall and spring gwl interpolations (rich's code)
d_sp <- readr::read_rds("RawData/lGF_SP2018.rds")
d_fa <- readr::read_rds("RawData/lGF_FA2018.rds")
d_19 <- readr::read_rds("RawData/lGF_2019.rds")

```

```{r Average Fall and Spring}
d_avg <- mean(d_fa$Prediction, d_sp$Prediction, d_19$Prediction)

plot(d_fa$Prediction)
plot(d_sp$Prediction, main = "2018 Spring Interpolation")
plot(d_19$Variance, main = "2019 Interpolation")
plot(d_avg, main = "Mean WSE \n(2018 and 2019)")

#d_project <- projectRaster(d, crs = crs(MTs[[1]]))
#writeRaster(d_avg, filename = "Avg2018_2019_WSE.tif", overwrite=TRUE)
```

```{r reproject MTs}
mt_merc <- list()

for(t in 1:length(MTs)){
  mt_merc[[t]] <- st_transform(MTs[[t]], CRS(proj4string(d_avg)))
}
# idk why mt_merc[[4]]'s coordinates are different, but here's a fix
mt_merc[[4]] <- st_zm(mt_merc[[4]], drop=TRUE)
# plot to make sure all looks okay
plot(d_avg)
#plot(mt_merc[[3]]$geometry, add=T)
for(t in 1:length(mt_merc)){
  plot(mt_merc[[t]]$geometry, add=TRUE) 
}
```

```{r Subtract GSP MTs from WSE}
extract_rastervals <- list()
# extract raster cell value where each monitoring well is located
for(m in 1:length(mt_merc)){
  extract_rastervals[[m]] <- raster::extract(d_avg, mt_merc[[m]])
}

# combine extracted values with existing shapefiles
finallist <- list()
for(a in 1:length(extract_rastervals)){
  finallist[[a]] <- cbind(mt_merc[[a]], extract_rastervals[[a]])
}

# rename extracted column
for(i in 1:length(extract_rastervals)){
  names(finallist[[i]])[3] <- "wse_18_19"
}

# find out how much each MT drops the water table
for(b in 1:length(extract_rastervals)){
  finallist[[b]]$diff_MT_wse <- finallist[[b]]$MT_dtw - finallist[[b]]$wse_18_19
  finallist[[b]]$diff_MT_wse <- ifelse(finallist[[b]]$diff_MT_wse<0, 0,  finallist[[b]]$diff_MT_wse)
}

# 5.3 % of MT wells were re-assigned a value of 0
sum(((sapply(finallist, function(x) x$diff_MT_wse) %>% unlist()) == 0), na.rm = TRUE) / length(sapply(finallist, function(x) x$diff_MT_wse) %>% unlist())

save.image(file = "GSP_MinimumThresholds.RData")
```

## Plot distributions
```{r Difference}
nam <- read_csv("~/Downloads/gsp_names.csv")

# take sampling distributions of 5, compute mean, and repeat 10,000 times
gen_sampling_dist_mean <- function(x) {
  replicate(1000,
            mean(sample(x$diff_MT_wse, size = 5, replace = TRUE), 
                 na.rm=TRUE)
  )
}

# subset to wells with a MT
mn2 <- lapply(finallist, function(x) x[!is.na(x$diff_MT_wse), ])
# take out wells that don't have enough MTs
nam <- nam[-29, ]
mn2[[29]] <- NULL

# generate sampling distributions of sample mean
bs <- vector("list", length = length(mn2))
for(i in 1:length(mn2)) {
  bs[[i]] <- data.frame(name = nam[i, 1],
                        z = gen_sampling_dist_mean(mn2[[i]]))
}

bind_rows(bs) %>%
  ggplot(aes(z)) +
  geom_line(stat="density") +
  facet_wrap(~GSP_Name, scales="free")


```

